stages:
  - Build image
  - Test acceptation

build:
  # Use the official docker image.
  image: docker:latest
  stage: Build image
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .

test acceptation:
  # Use the official docker image.
  image: docker:latest
  stage: Test acceptation
  services:
    - docker:dind
  script:
    - docker run -d --name webapp alpinehelloimage
